name: sns_flutter
description: "A App helpful to middle school students."
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  pocketbase: ^0.18.1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.8.4
  table_calendar: ^3.0.6
  intl: ^0.19.0
  font_awesome_flutter: ^9.2.0
  introduction_screen: ^3.1.14
  shared_preferences: ^2.0.6
  get: ^4.6.6
  dio: ^5.5.0+1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  kakao_flutter_sdk: ^1.9.0
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.1.0
  pull_to_refresh: ^2.0.0
  google_sign_in: ^6.2.1
  flutter_provider: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png
  - assets/images/apple_logo.svg
  - assets/images/kakao_logo.svg
  - assets/images/google_logo.svg
  - assets/images/insta_logo.svg
  - assets/images/github_logo.svg
  - assets/images/darwin_title.png
  - assets/images/profile.svg
